# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3441d88b134e3c2a27673bfff0545e18618f3d76374921a69f73a1d354602075b2bd6a7b9656645fd55a700a01df83798ccd2a4747b01d4efe9697b640d957fa

test:
  secret_key_base: 71d06ad745465f7fb58e7f8318823ca6dbb6638b0419fef2c1c7781618dcbd0c745f5e9707d141d64ec64b20288e09821dab6583abb4a5b5f5b601b949a93084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
