# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbcb5ddd07a35373661b6d2d7e3597a47bd02b81ec1810312c470501c555a231c19d1c34372b2cdb685a3fdf6df71861d7af0e849f07a1f4e19a3653f3d5ae18

test:
  secret_key_base: a5c19f34848f866678a5eef795c9a1d97e9aede9494a6df66ba7639ca67bb6899aa20ad431f0b39764782cb2d276238037fd12c3084f5ee1b47552cc39c7828f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
