# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739923d5dd0c9b1f23ae1b446edaea96d6d4d7c1b5980727634afb03d724ba02a0d768058225bc193b836bb1505ac36d05e8c4c8c0b604e21fa5942a337f87c0

test:
  secret_key_base: af94fe36048be1beeb4ee1d059721d93c8491d89aa668d34bbd8d948d5500dfad62304b5efbf0d2ced837adf5dec84526f2a05e03212a83c1dc52b332154cf7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
