# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55fe89565a4d3079ffbc4a588bec51fba2cf999d8ff56d214bc78885f12145b3f8bdb911e04b1279e7525021b1ad01876ad15e4527205227c248a41a08be44bf

test:
  secret_key_base: d9a4cd89728ff12d72f48e8618346127b2fd60543d84e4bc6a96dce89b3a4e1471f92a0b725cbab5399cbfb638280dd8c837510115d86b51929c04a3f49f49ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
